name: Encode 480p VVC

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Rescale from y4m to 480p y4m
        run: |
          cd E:\
          E:
          ffmpeg -i tearsofsteel-4k.y4m -vf scale=854x356 -pix_fmt yuv420p -strict 1 tearsofsteel-480p.y4m
      - name: Check versions of installed
        run: | 
          vvencapp --version
          mp4box -version
      - name: Encode from Y4M to VVC
        run: |
          cd E:\
          E:
          vvencapp -i tearsofsteel-480p.y4m -s 854x356 -r 24 --preset slow --qp 35 --tier high -o tearsofsteel-480p.266
      - name: Check .266 file info with mp4box
        run: |
          cd E:\
          E:
          mp4box -no-probe -info tearsofsteel-480p.266
      - name: Check SHA256SUM of 266 file
        run: |
          cd E:\
          E:
          certutil -hashfile tearsofsteel-480p.266 SHA256
