name: Encode VVC video

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Rescale from y4m to 1080p y4m
        run: |
          cd E:\
          E:
          ffmpeg -i tearsofsteel-4k.y4m -vf scale=1920x800 -pix_fmt yuv420p -strict 1 tearsofsteel-1080p.y4m
      - name: Check versions of installed
        run: | 
          vvencapp --version
          mp4box -version
      - name: Encode from Y4M to VVC
        run: |
          cd E:\
          E:
          vvencapp -i tearsofsteel-1080p.y4m -s 1920x800 -r 24 --preset slow --qp 35 --tier high -o tearsofsteel-1080p.266
      - name: Check .266 file info with mp4box
        run: |
          cd E:\
          E:
          mp4box -no-probe -info tearsofsteel-1080p.266
      - name: Check SHA256SUM of 266 file
        run: |
          cd E:\
          E:
          certutil -hashfile tearsofsteel-1080p.266 SHA256
